## Importing Libraries

In [12]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
import numpy as np

## Defining dataset

In [2]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

### Encoding dataser

In [3]:
le = preprocessing.LabelEncoder()

In [4]:
weather_encoded = le.fit_transform(weather)
weather_encoded # sunny = 2 overcast = 0, Rainy = 1

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1], dtype=int64)

In [22]:
temp_encoded = le.fit_transform(temp)
temp_encoded #Hot = 1, Mild = 2 Cool = 0 

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2], dtype=int64)

In [23]:
label = le.fit_transform(play)
label # No = 0, play = 1

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [20]:
features = []
[features.append(i) for i in zip(weather_encoded, temp_encoded)]
features

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

## Training model

In [21]:
model = GaussianNB()
model.fit(features, label)

GaussianNB(priors=None, var_smoothing=1e-09)

## Testing mode

In [29]:
predicted = model.predict([[2, 2]])
predicted

array([0], dtype=int64)